In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv('Solar Energy.csv')

In [7]:
df.head(5)

,Data Through Date,Project ID,Interconnection Date,Utility,City/Town,County,Zip,Division,Substation,Circuit ID,Developer,Metering Method,Estimated PV System Size (kWdc),PV System Size (kWac),Estimated Annual PV Energy Production (kWh),Energy Storage System Size (kWac),Number of Projects
0,12/31/2023,SDG-66301,12/29/2023,Con Ed,Richmond Hill,Queens,11418.0,CENY-BK,Brownsville_2,9B05,Kamtech Solar Solutions,NM,6.05,5.17,7100,NaN,1
1,12/31/2023,SDG-66299,12/29/2023,Con Ed,Bronx,Bronx,10473.0,CENY-BX,Parkchester_2,5X67,Kamtech Solar Solutions,NM,6.74,5.76,7911,NaN,1
2,12/31/2023,SDG-66288,12/29/2023,Con Ed,Brooklyn,Kings,11225.0,CENY-BK,Bensonhurst_2,4B08,SUNCO,NM,3.05,2.61,3585,NaN,1
3,12/31/2023,SDG-66284,12/29/2023,Con Ed,Brooklyn,Kings,11236.0,CENY-BK,Bensonhurst_2,3037,Kamtech Solar Solutions,NM,5.62,4.80,6592,NaN,1
4,12/31/2023,SDG-66277,12/28/2023,Con Ed,Springfield Gardens,Queens,11413.0,CENY-Q,Jamaica,9112,Kamtech Solar Solutions,NM,6.05,5.17,7100,NaN,1

In [13]:
df.shape

(218115, 17)

In [15]:
df.describe

<bound method NDFrame.describe of        Data Through Date Project ID Interconnection Date Utility  \
0             12/31/2023  SDG-66301           12/29/2023  Con Ed
1             12/31/2023  SDG-66299           12/29/2023  Con Ed
2             12/31/2023  SDG-66288           12/29/2023  Con Ed
3             12/31/2023  SDG-66284           12/29/2023  Con Ed
4             12/31/2023  SDG-66277           12/28/2023  Con Ed
...                  ...        ...                  ...     ...
218110        12/31/2023       49.0           12/19/2002     RGE
218111        12/31/2023       48.0            9/24/2002     RGE
218112        12/31/2023        NaN             7/1/2018  PSEGLI
218113        12/31/2023        NaN             3/3/2018  PSEGLI
218114        12/31/2023        NaN            11/1/2011  PSEGLI

                  City/Town    County      Zip  Division  \
0             Richmond Hill    Queens  11418.0   CENY-BK
1                     Bronx     Bronx  10473.0   CENY-BX
2                  Brooklyn     Kings  11225.0   CENY-BK
3                  Brooklyn     Kings  11236.0   CENY-BK
4       Springfield Gardens    Queens  11413.0    CENY-Q
...                     ...       ...      ...       ...
218110              Ontario     Wayne  14519.0     Sodus
218111           Friendship  Allegany  14739.0  Fillmore
218112                  NaN   Suffolk  11786.0       NaN
218113                  NaN   Suffolk  11933.0       NaN
218114                  NaN   Suffolk  11973.0       NaN

                           Substation  Circuit ID                Developer  \
0                       Brownsville_2        9B05  Kamtech Solar Solutions
1                       Parkchester_2        5X67  Kamtech Solar Solutions
2                       Bensonhurst_2        4B08                    SUNCO
3                       Bensonhurst_2        3037  Kamtech Solar Solutions
4                             Jamaica        9112  Kamtech Solar Solutions
...                               ...         ...                      ...
218110        0205LS0237-1589 RTE 104  0205LS0237                      NaN
218111  8333GV7702-Friendship Nile RD  8333GV7702                      NaN
218112                            NaN         NaN                      NaN
218113                            NaN         NaN                      NaN
218114                            NaN         NaN                      NaN

       Metering Method  Estimated PV System Size (kWdc)  \
0                   NM                             6.05
1                   NM                             6.74
2                   NM                             3.05
3                   NM                             5.62
4                   NM                             6.05
...                ...                              ...
218110              NM                             2.81
218111              NM                             2.93
218112             FIT                         34362.00
218113             FIT                         27600.00
218114             FIT                         43470.00

        PV System Size (kWac)  Estimated Annual PV Energy Production (kWh)  \
0                        5.17                                         7100
1                        5.76                                         7911
2                        2.61                                         3585
3                        4.80                                         6592
4                        5.17                                         7100
...                       ...                                          ...
218110                   2.40                                         3296
218111                   2.50                                         3433
218112               24900.00                                     40335490
218113               20000.00                                     32397984
218114               31500.00                                     51026825

        Energy Storage System Size (kWac)  Number of Projects
0                                     NaN                   1
1                                     NaN                   1
2                                     NaN                   1
3                                     NaN                   1
4                                     NaN                   1
...                                   ...                 ...
218110                                NaN                   1
218111                                NaN                   1
218112                                NaN                   1
218113                                NaN                   1
218114                                NaN                   1

[218115 rows x 17 columns]>

In [17]:
df.columns

Index(['Data Through Date', 'Project ID', 'Interconnection Date', 'Utility',
       'City/Town', 'County', 'Zip', 'Division', 'Substation', 'Circuit ID',
       'Developer', 'Metering Method', 'Estimated PV System Size (kWdc)',
       'PV System Size (kWac)', 'Estimated Annual PV Energy Production (kWh)',
       'Energy Storage System Size (kWac)', 'Number of Projects'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218115 entries, 0 to 218114
Data columns (total 17 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Data Through Date                            218115 non-null  object
 1   Project ID                                   218112 non-null  object
 2   Interconnection Date                         218115 non-null  object
 3   Utility                                      218115 non-null  object
 4   City/Town                                    218057 non-null  object
 5   County                                       218115 non-null  object
 6   Zip                                          218019 non-null  float64
 7   Division                                     132881 non-null  object
 8   Substation                                   138171 non-null  object
 9   Circuit ID                                   218085 non-null  object
 10  Developer                                    207565 non-null  object
 11  Metering Method                              217652 non-null  object
 12  Estimated PV System Size (kWdc)              218115 non-null  float64
 13  PV System Size (kWac)                        218115 non-null  float64
 14  Estimated Annual PV Energy Production (kWh)  218115 non-null  int64
 15  Energy Storage System Size (kWac)            4091 non-null    float64
 16  Number of Projects                           218115 non-null  int64
dtypes: float64(4), int64(2), object(11)
memory usage: 28.3+ MB

In [21]:
df.describe()

,Zip,Estimated PV System Size (kWdc),PV System Size (kWac),Estimated Annual PV Energy Production (kWh),Energy Storage System Size (kWac),Number of Projects
count,218019.000000,218115.000000,218115.000000,2.181150e+05,4091.000000,218115.0
mean,11751.734473,24.507977,19.065451,2.876828e+04,32.174727,1.0
std,962.129108,291.525394,211.419642,3.422042e+05,296.161116,0.0
min,10001.000000,0.010000,0.010000,1.400000e+01,0.350000,1.0
25%,11220.000000,5.270000,4.500000,6.180000e+03,5.000000,1.0
50%,11717.000000,7.130000,6.090000,8.364000e+03,7.600000,1.0
75%,12018.000000,10.240000,8.750000,1.201700e+04,10.000000,1.0
max,14905.000000,43470.000000,31500.000000,5.102682e+07,5000.000000,1.0

In [25]:
df.isna().sum()

Data Through Date                                   0
Project ID                                          3
Interconnection Date                                0
Utility                                             0
City/Town                                          58
County                                              0
Zip                                                96
Division                                        85234
Substation                                      79944
Circuit ID                                         30
Developer                                       10550
Metering Method                                   463
Estimated PV System Size (kWdc)                     0
PV System Size (kWac)                               0
Estimated Annual PV Energy Production (kWh)         0
Energy Storage System Size (kWac)              214024
Number of Projects                                  0
dtype: int64